hypha-dao/dao-contracts

dao-go/assignments_test.go
dao-go/badges_test.go
dao-go/edit_test.go
dao-go/helpers_test.go
dao-go/payout_test.go
dao-go/proposal_test.go
dao-go/proposals.go
include/common.hpp
include/dao.hpp
include/proposals/proposal.hpp
include/trail.hpp
src/dao.cpp
src/proposals/proposal.cpp

Depends on https://github.com/hypha-dao/document-graph/pull/19

Initial changes on the ballot propose

---

include/dao.hpp

added the payments table back, which still has data. We'll hold this table around for a little bit longer just in case. There's also a ```erasepymts``` action that will erase all of them when we are ready. It's all in dao.hpp

added the payments table back - for deletion in March

---

CMakeLists.txt
dao-go/decide.go
dao-go/environment_test.go
dao-go/proposal_test.go
include/proposals/proposal.hpp
src/proposals/proposal.cpp

- Added itest within dao to verify it works

Backwards compatbility for closing proposals created with telos

---

dao-go/assignments_test.go
include/common.hpp
include/period.hpp
src/assignment.cpp
src/dao.cpp
src/period.cpp
src/proposals/ass_extend_proposal.cpp
src/proposals/assignment_proposal.cpp
src/proposals/edit_proposal.cpp
src/proposals/proposal.cpp

+ Moved approved date item to system group 
+ Added checks for expired assignments on edit proposals
+ Added edit assignment test

Proposal updates

---

include/proposals/proposal.hpp
src/proposals/proposal.cpp

+ Restored check for ballot_title item (edit proposals) 
+ Added check for ballot_description item (edit proposals)

restored check for ballot title & added check for ballot description

---

src/proposals/edit_proposal.cpp

+ Added check on `EditAssignment:getBallotContent ` for ballot_title/title items

added check for ballot title within edit proposal

---

dao-go/proposal_test.go
src/ballots/vote.cpp
src/ballots/vote_tally.cpp

Depends on https://github.com/hypha-dao/document-graph/pull/28

Fix ballots

---

.github/workflows/build.yaml
README.md

Add github action to ensure the code builds.
Also updates document-graph to latest develop (it wasn't compiling)

Add github action to build the code

---

src/dao.cpp

- Code was trying to get **NODE_LABEL** item from the wrong content group **DETAILS**.

Memo is not fetching the node_label

---

tests/dao/DaoBlockchain.ts
tests/types/Document.ts
tests/types/Periods.ts

- Sending actions in batches
- Computing some hashes before sending (to be able to batch)

Optimizations on tests (setup)

---

include/common.hpp
include/proposals/payout_proposal.hpp
include/proposals/quest_completion_proposal.hpp
include/proposals/quest_start_proposal.hpp
src/CMakeLists.txt
src/proposals/payout_proposal.cpp
src/proposals/proposal_factory.cpp
src/proposals/quest_completion_proposal.cpp
src/proposals/quest_start_proposal.cpp

Allows to create Quest Start Proposals

---

src/dao.cpp
src/proposals/payout_proposal.cpp

pause claims - needs to be deployed to dao.hypha

pause claims

---

src/proposals/badge_assignment_proposal.cpp

- Fixes assigning a member the same badge more than once

fixed reassigning badge

---

src/dao.cpp

As per requirements, when people buy HYPHA with HUSD, it goes in the cosale contract.

pay HUSD purchases to costake contract

---

src/proposals/proposal.cpp

Allows suspend proposals to have a longer title

---

include/proposals/badge_assignment_proposal.hpp
src/proposals/badge_assignment_proposal.cpp

- Moved the creation of the badge edge from the proposal approval to the proposal creation step

Moved badge edge creation from passImpl to postProposeImple

---

include/ballots/vote.hpp
include/ballots/vote_tally.hpp
include/comments/comment.hpp
include/comments/likeable.hpp
include/comments/section.hpp
include/typed_document.hpp
include/typed_document_factory.hpp
src/CMakeLists.txt
src/ballots/vote.cpp
src/ballots/vote_tally.cpp
src/comments/comment.cpp
src/comments/likeable.cpp
src/comments/section.cpp
src/dao.cpp
src/typed_document.cpp
src/typed_document_factory.cpp
tests/comments.test.ts
tests/dao/DaoBlockchain.ts

and other refactorings to TypedDocuments
- Removing template to simplify the type

Adding likes to comment

---

include/common.hpp
src/dao.cpp

- Added dao_url setting for DAO's
- Added check to verify if dao_url already exists when editing it

added dao_url on dao creation & check on setdaosetting for repeated urls

---

include/common.hpp
include/dao.hpp
include/util.hpp
src/dao.cpp

Added modsalaryband action to enable adding/editing/deleting salary band documents for DAOS

Compensation Config

---

include/dao.hpp
include/time_share.hpp
include/util.hpp
src/dao.cpp
src/time_share.cpp
src/util.cpp

Adds two actions to enable simulating claiming all the available periods for a give assignment or all the assignments of an specified user

Simulated Claims

---

templates/config/production.config.hpp

This is so we can deploy on EOS

remove pricing plan and upvote from prod

---

include/dao.hpp
setup/init.js
src/dao.cpp

adding createroot back in
